// <auto-generated />
using DG.Momenton.Infrastructure.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace DG.Momenton.Infrastructure.Migrations
{
    #region SetupEmployee

    /// <summary>
    /// This used to create/migrate the database via EF Code-First
    /// This class is auto-generated via running "Add-Migration SetupEmployee" command on Package-Manager-Console
    /// </summary>
    [DbContext(typeof(DataContext))]
    [Migration("20180529043451_SetupEmployee")]
    partial class SetupEmployee
    {
        #region BuildTargetModel

        /// <summary>
        /// Build the target DB model
        /// </summary>
        /// <param name="modelBuilder"></param>
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DG.Momenton.Infrastructure.Repository.Models.Employee", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("ManagerId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }

        #endregion
    }

    #endregion
}
