// <auto-generated />
using DG.Momenton.Infrastructure.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DG.Momenton.Infrastructure.Migrations
{
    /// <summary>
    /// The snapshot for the DataContext
    /// This class is auto-generated via running "Add-Migration SetupEmployee" command on Package-Manager-Console
    /// </summary>
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        #region BuildModel

        /// <summary>
        /// Build the snapshot model
        /// </summary>
        /// <param name="modelBuilder"></param>
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DG.Momenton.Infrastructure.Repository.Models.Employee", b =>
                {
                    b.Property<int>("Id");

                    b.Property<int?>("ManagerId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }

        #endregion
    }
}
